### ISSUE TITLE
How to align the output mannequin with the original image

### ISSUE THREAD

**Issue by wangguangyuan** [YuliangXiu/ICON#10]
Thank you so much for such an excellent work open source．
I would like to ask if the human model output by the network is aligned with the original input image．I see that the input image will be processed．

I see that the input image will be processed. If I have multi-view input images, I want to fuse these images and get a mannequin into one mannequin. How to do it.

**Comment by YuliangXiu** [comment]
1. If your input image is square, just change the `has_det=False` in [infer.py](https://github.com/YuliangXiu/ICON/blob/master/apps/infer.py#L87)
2. otherwise, you can still align the output mesh with the original input image, [imutils.py](https://github.com/YuliangXiu/ICON/blob/c88a52cbf13d26f252297985019017073feba4cf/lib/pymaf/utils/imutils.py#L98) contains the functions for bbox detection and cropping. These functions transform input image into a square image, and the final reconstruction mesh is aligned with the square image. So to align with the original image, the only thing you need to do is to **inverse the cropping**.

**Comment by YuliangXiu** [comment]
@wangguangyuan ICON now supports the **overlap** between the original input image and the predicted normal map.

Please see [infer.py](https://github.com/YuliangXiu/ICON/blob/master/apps/infer.py#L285)

![overlap](https://user-images.githubusercontent.com/7944350/153779064-142e57ff-4d2f-403f-abc7-01f2b8ad7bc5.gif)
