### ISSUE TITLE
How to make the ICON output mesh move (novel pose) by changing the smpl params?

### ISSUE THREAD

**Issue by cocoshe** [YuliangXiu/ICON#156]
I use a image as input to run ICON, then I get a mesh.
Q1: I don't want to use SCANimate to rig the bones, and just use the smpl. Though the quality would be not that good, but I want the speed, so can't contain "train" step. So how can I warp the output mesh? For example, change the complex pose to T-pose.

Q2: How can I get the color mesh? I noticed that the output mesh "XXX_refine" only get the color in where the origin image show, so any methods to get the full color of the mesh? I know it's not possible to get the color behind the mesh because the input is only one image without color behind the person.  
But any other ways to paint the color on mesh first, then do the work in Q1, warp the mesh to T-pose?

**Comment by YuliangXiu** [comment]
Since we already have the underneath SMPL, which contains the skeleton, bone rotation matrix and skinning weights, then the ICON reconstruction could be animated with the help of them, the only thing you need to change is the new per-vertex skinning weights because the topology of ICON is different with SMPL.

I will support this feature later, but if you need it very urgently, you could implement it by yourself, which is not very difficult.

As for the texture inpainting, this is almost a standalone project. PIFu's solution could not generalize well to various clothing textures, **view-consistency texture generation conditioned on front-view** seems more promising, I am working on it for now. But there is no guarantee for the release.

**Comment by cocoshe** [comment]
> Since we already have the underneath SMPL, which contains the skeleton, bone rotation matrix and skinning weights, then the ICON reconstruction could be animated with the help of them, the only thing you need to change is the new per-vertex skinning weights because the topology of ICON is different with SMPL.
> 
> I will support this feature later, but if you need it very urgently, you could implement it by yourself, which is not very difficult.
> 
> As for the texture inpainting, this is almost a standalone project. PIFu's solution could not generalize well to various clothing textures, **view-consistent texture generation conditioned on front-view** seems more promising, I am working on it for now. But there is no guarantee for the release.

I don't understand clearly what does "skinning weights", it means the params weights in SMPL model? I'm wondering if I can make ICON mesh move with the rigged skinning weight of SMPL template, or I must do re-rigging the skinning on the ICON mesh?

**Comment by cocoshe** [comment]
Another question, SCANimate require the ’ply‘ format, but ICON output mesh is 'obj', it can be use directly or what need to be done to ICON output?

**Comment by YuliangXiu** [comment]
> > Since we already have the underneath SMPL, which contains the skeleton, bone rotation matrix and skinning weights, then the ICON reconstruction could be animated with the help of them, the only thing you need to change is the new per-vertex skinning weights because the topology of ICON is different with SMPL.
> > I will support this feature later, but if you need it very urgently, you could implement it by yourself, which is not very difficult.
> > As for the texture inpainting, this is almost a standalone project. PIFu's solution could not generalize well to various clothing textures, **view-consistent texture generation conditioned on front-view** seems more promising, I am working on it for now. But there is no guarantee for the release.
> 
> I don't understand clearly what does "skinning weights", it means the params weights in SMPL model? I'm wondering if I can make ICON mesh move with the rigged skinning weight of SMPL template, or I must do re-rigging the skinning on the ICON mesh?

You can make ICON move with rigged skinning weights from SMPL template, no need to do re-rigging, since skeleton and bone rotation matrix are available in SMPL-X, and the skinning weights can be transfered from SMPL-X to ICON using nearest neighbor searching.

`ply` is just another format of `obj`, they are same for `trimesh.load`

**Comment by YuliangXiu** [comment]
@cocoshe 

ECON now supports full texture generation w/ the help of TEXTure

https://github.com/YuliangXiu/ECON#texture

[1] Richardson E, Metzer G, Alaluf Y, et al. Texture: Text-guided texturing of 3d shapes[J]. arXiv preprint arXiv:2302.01721, 2023.
