### ISSUE TITLE
pifu code

### ISSUE THREAD

**Issue by z-z-zhao** [YuliangXiu/ICON#219]
您好，我看了您的ICON的仓库，其中关于PIFu的代码。我有了一些疑问，在2019年的PIFu论文中并没有使用法线的特征，为什么关于PIFu的您的代码中有法线的使用？
![法线？](https://github.com/YuliangXiu/ICON/assets/57577944/2b66792f-f85b-403f-9244-ec5428134ecb)
另外您还使用了smpl的特征？（PIFu论文中并没有使用smpl）如下图：

![其他特征](https://github.com/YuliangXiu/ICON/assets/57577944/8f9b13d4-9b0c-4fe5-b84d-08b10a1896d7)
恳请您帮助解决我的疑问！十分感谢！！！

**Comment by z-z-zhao** [comment]
2019年的PIFu(https://github.com/shunsukesaito/PIFu)

**Comment by z-z-zhao** [comment]
PIFu: Pixel-Aligned Implicit Function for High-Resolution Clothed Human Digitization

**Comment by YuliangXiu** [comment]
In my re-implemented PIFu, called PIFu* in original paper:
- We do use normal maps to better align with other re-implemented methods, e.g., PaMIR, ICON. In this way, we can claim that the performance boost mainly comes from method novelty, instead of the input types.
- But PIFu* does not extract local features from SMPL ([HGPIFuNet.py#L126](https://github.com/YuliangXiu/ICON/blob/master/lib/net/HGPIFuNet.py#L126)), it only uses image+normal as input.

**Comment by z-z-zhao** [comment]
in your "But PIFu* does not extract local features from SMPL (please go deeper into HGPIFuNet.py#L126), it only uses image+normal as input". is PIFu(your code) or PIFu*  (original paper) ?

As far as I know, PIFu* (original paper) did not use normals and it just use image,but PIFuHD used forward and backward normals + image.
This is very important to me and I look forward to your reply！

**Comment by YuliangXiu** [comment]
I updated the last reply, PIFu* is from ICON's paper.

PIFu (original): use image as input
PIFuHD: use image+normals(front+back) as input
PIFu* (ICON's re-implementation): use image+normals(front+back, SMPL-conditioned) as input
