### ISSUE TITLE
How many FPS can you achieve？

### ISSUE THREAD

**Issue by favorxin** [YuliangXiu/ICON#22]
It‘s a great work! I have a question about the FPS. Can it achieve real-time?

**Comment by YuliangXiu** [comment]
Due to the **normal-based SMPL optimization**, ICON can't achieve real-time speed for now. We use 100 iterations, and each iteration takes ∼460 ms on a Quadro RTX 5000 GPU. But I guess it can achieve real-time speed if we can:

1. drop the optimization module
2. replace PyMAF with real-time HPS, e.g. DetNet [1]
3. use SMPL mesh to reduce the query time of implicit inference


[1] Zhou, Yuxiao, et al. "Monocular real-time full body capture with inter-part correlations." Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2021.

**Comment by hygenie1228** [comment]
Hi, thanks for your great work.
I also have a question about the inference time.
What is the average inference time per image, including the refinement loop?

**Comment by YuliangXiu** [comment]
20~30s per image (100 iters for SMPL optimization)

**Comment by Yuhuoo** [comment]
Thank you for your excellent work! May I ask if you can provide the code for calculating inference speed?
