### ISSUE TITLE
Difference between inference code and evaluation code?

### ISSUE THREAD

**Issue by ZZWENG** [YuliangXiu/ICON#246]
Hi authors, I noticed a difference in the predicting mesh using inference and evaluation code.

Specifically, for THuman 2.0 human id 506, the predicted meshes from running inference code for the `PiFU` model
`python -m apps.infer -cfg ./configs/pifu.yaml -gpu 0 -in_dir data/thuman2_36views/0506/render`
and testing code
`python -m apps.train -cfg ./configs/train/pifu.yaml -test`
are different. 

See in the below image. Left is inference code. Right is testing code. The input image have the same input view.

<img width="1222" alt="Screenshot 2024-01-27 at 2 00 12 PM" src="https://github.com/YuliangXiu/ICON/assets/6405424/2f510d50-f665-49bc-a272-0aaaff7f5d39">

Input image
![000](https://github.com/YuliangXiu/ICON/assets/6405424/bb0eef14-594f-4aca-8716-bd1c247f8e04)

Could you please help clarify why this is the case? Thank you in advance!

**Comment by YuliangXiu** [comment]
In the `inference` mode, the SMPL-X body is estimated using off-the-shelf methods, such as PIXIE or PyMAF.

However, in the `evaluation` mode, we use ground-truth SMPL-X body to filter out the influence of body misalignment. Thus, the final reported numbers could solely reflect the reconstruction performance of **clothing** instead of the **body pose**.

**Comment by ZZWENG** [comment]
Hi, thank you for your quick response! But the model I am using the PiFU model, which does not use body prior at all.
