### ISSUE TITLE
ModuleNotFoundError: No module named 'bvh_distance_queries_cuda'

### ISSUE THREAD

**Issue by Pallab38** [YuliangXiu/ICON#5]
Hi, thank you so much for the wonderful work and corresponding codes. I am facing the following issue: 
https://github.com/YuliangXiu/ICON/blob/0045bd10f076bf367d25b7dac41d0d5887b8694f/lib/bvh-distance-queries/bvh_distance_queries/bvh_search_tree.py#L27

Is there any .py file called ``` bvh_distance_queries_cuda ``` ? Please let me know a possible solution. 
Thank you for your effort and help :) :) :)

**Comment by YuliangXiu** [comment]
Have you installed or compiled all the required packages in [installation](https://github.com/YuliangXiu/ICON/blob/master/docs/Installation.md#required-packages-ubuntu-20043-lts-cuda110)?

This package comes from [cuda src](https://github.com/YuliangXiu/ICON/blob/master/lib/bvh-distance-queries/setup.py#L70), the error should be fixed after compiling the `bvh-distance-queries`.

**Comment by Pallab38** [comment]
I missed/overlooked that ```installation``` page. I am sorry. Thank you so much for your help. :) :) :)

**Comment by 1kaiser** [comment]
colab version anytime ??

**Comment by YuliangXiu** [comment]
> colab version anytime ??

soon

**Comment by 1kaiser** [comment]
`!git clone https://github.com/YuliangXiu/ICON.git`
`!cd /content/ICON`

`!pip install -r /content/ICON/requirements.txt`

`# install rembg`
`!GPU=1 pip install rembg --upgrade`

`# install neural_renderer`
`#cuda >= 11.0`
`!git clone https://github.com/adambielski/neural_renderer.git`
`!cd neural_renderer && python setup.py install`
`# cuda < 11.0`
`!pip install neural_renderer_pytorch`

`# install smplx (modified by @Yuliang Xiu)`
`!git clone https://github.com/YuliangXiu/smplx.git`
`!cd smplx && python setup.py install`

`# install bvh-distance-queries`
`!cd /content/ICON/lib/bvh-distance-queries && git clone https://github.com/NVIDIA/cuda-samples.git `
`!cd /content/ICON/lib/bvh-distance-queries && export CUDA_SAMPLES_INC='/content/ICON/lib/bvh-distance-queries/cuda-samples/Common' && python setup.py install`


and to download the required files we had to ligin from lots of sites 
since everyone would be directly running the code in colab

little backend file downloading and resarranging to structyure is also required
![Screenshot 2022-02-03 191533](https://user-images.githubusercontent.com/26379748/152354838-9988e88f-5f8d-4497-bc3b-abd5dd7653e9.png)


**Pre-trained models and extra data**

`!mkdir -p /content/data/pymaf_data/a/aa`
`!wget http://visiondata.cis.upenn.edu/spin/data.tar.gz -O /content/data/pymaf_data/data.tar.gz && tar xvf /content/data/pymaf_data/data.tar.gz -C /content/data/pymaf_data/a/aa `
`!mv /content/data/pymaf_data/a/aa/data/* /content/data/pymaf_data`
`!rm -r /content/data/pymaf_data/a /content/data/pymaf_data/data.tar.gz`


**SMPL (10 shape PCs)**
`!wget --post-data "username=tikaxof667@rippb.com&password=i4tSMU@94UNbuFK" 'https://download.is.tue.mpg.de/download.php?domain=smpl&sfile=SMPL_python_v.1.0.0.zip&resume=1' -O '/content/data/SMPL.zip' --no-check-certificate --continue`
`!mkdir -p /content/data/a/aa`
`!unzip /content/data/SMPL.zip -d /content/data/a/aa`
`!mv /content/data/a/aa/smpl/models/basicModel_f_lbs_10_207_0_v1.0.0.pkl /content/data/smpl_related/models/smpl/SMPL_FEMALE.pkl`
`!mv /content/data/a/aa/smpl/models/basicmodel_m_lbs_10_207_0_v1.0.0.pkl /content/data/smpl_related/models/smpl/SMPL_MALE.pkl`
`!rm -r /content/data/SMPL.zip /content/data/a`


**SMPLIFY_CODE_V2.ZIP**
`!wget --post-data "username=tikaxof667@rippb.com&password=i4tSMU@94UNbuFK" 'https://download.is.tue.mpg.de/download.php?domain=smplify&sfile=mpips_smplify_public_v2.zip&resume=1' -O '/content/data/SMPL_neutral.zip' --no-check-certificate --continue`
`!mkdir -p /content/data/a/aa`
`!unzip /content/data/SMPL_neutral.zip -d /content/data/a/aa`
`!mv /content/data/a/aa/data/smplify_public/code/models/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl /content/data/smpl_related/models/smpl/SMPL_NEUTRAL.pkl`
`!rm -r /content/data/a /content/data/SMPL_neutral.zip`

**Download [ICON]**
`!wget --post-data "username=tikaxof667@rippb.com&password=i4tSMU@94UNbuFK" 'https://download.is.tue.mpg.de/download.php?domain=icon&sfile=icon_data.zip&resume=1' -O '/content/data/icon_data.zip' --no-check-certificate --continue`
`!mkdir -p /content/data/a/aa`
`!unzip /content/data/icon_data.zip -d /content/data/a/aa`
`!mv /content/data/a/aa/smpl_data /content/data/smpl_related`
`!rm -r /content/data/a /content/data/icon_data.zip`

**Comment by YuliangXiu** [comment]
@1kaiser 

<a href="https://colab.research.google.com/drive/1-AWeWhPvCTBX0KfMtgtMk10uPU05ihoA?usp=sharing" style="padding-left: 0.5rem;"> <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Google Colab" /> </a>
