### ISSUE TITLE
Question about experiments in optimization SMPL during training

### ISSUE THREAD

**Issue by MooreManor** [YuliangXiu/ICON#85]
Hello, Yuliang! Thanks for your great work!

In the **Refining SMPL** section of your paper, you said that the results of inferred clothed normals could supervise SMPL mesh to be more pixel-aligned, and at the same time an optimized SMPL mesh could contribute to more reliable and detailed clothed normals. 

Since the refining SMPL process is useful as we can see from the experiments, I wonder if you have done some experiments to optimize the SMPL mesh in some ways (e.g. clothed normals) during training?

**Comment by YuliangXiu** [comment]
The refinement process only applies during testing. Instead, we use ground-truth / perturbed SMPL-(X) fits during training without any refinement.

**Comment by MooreManor** [comment]
@YuliangXiu Thank you for your kind reply!

I want to know do you do any experiments about SMPL optimization with clothed normal or something else when training. Was the above optimization useless in training, or you just didn't try the optimized experiments during training?

**Comment by YuliangXiu** [comment]
I didn't do such refinement during training, because the perturbed SMPL-(X) fits already provide such misalignment noise during training. You can check [config](https://github.com/YuliangXiu/ICON/blob/master/configs/train/icon-filter.yaml#L25) to get more details about how we add the noise during training.
