### ISSUE TITLE
SDF CLIP

### ISSUE THREAD

**Issue by EadCat** [YuliangXiu/ICON#99]
Hi, By what standard did you measure the self.sdf_clip?
https://github.com/YuliangXiu/ICON/blob/cf46a6b6ff5a0073268db9e27a259ae2de41bc59/lib/net/HGPIFuNet.py#L70

I'm using PaMIR's scale, so should I do 1/100 of self.sdf_clip based on THuman2.0's scale?
PaMIR Normalize Code: https://github.com/ZhengZerong/PaMIR/blob/main/data/main_normalize_mesh.py

**Comment by YuliangXiu** [comment]
Since SDF didn't outperform Occupancy in our experiments, we finally all used occupancy loss for training. Thus these lines could be deleted. 

`self.sdf_clip` was used to convert SDF to TSDF, in other words, those points which are far away from body mesh should all be truncated as a const value. Thus, it's okay to remove the `/ 100.0` if the SDF is already calculated in [-1, 1] normalized space.

**Comment by EadCat** [comment]
As you said, The SMPL-X coordinates are in [-1, 1] space.

I used self.sdf_clip = 15.0 and finished my reproducing.

Really appreciate it !!
